name: Build Game Bethesda Library

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: windows-2022
    steps:
      # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          setup-python: false
          version: 6.7.0
          modules:
          cache: true

      - uses: actions/checkout@v4
      - uses: lukka/run-vcpkg@v11

      - name: Configure Game Bethesda
        shell: pwsh
        run: |
          cmake --preset vs2022-windows-standalone `
            "-DCMAKE_PREFIX_PATH=${env:QT_ROOT_DIR}\msvc2019_64" `
            "-DCMAKE_INSTALL_PREFIX=install"

      - name: Build Game Bethesda
        run: cmake --build vsbuild --config RelWithDebInfo --target INSTALL
